### ISSUE TITLE
Application cant run

### ISSUE THREAD

**Issue by stardock** [voidbar/forwardgram#14]
Is the Chinese group name not supported?
Below is the output

2020-03-11 08:57:28,282 - telethon.extensions.messagepacker - DEBUG - Assigned msg_id = 6802748226810135608 to InvokeWithLayerRequest (7f9d8ac93f60)
2020-03-11 08:57:28,282 - telethon.network.mtprotosender - DEBUG - Encrypting 1 message(s) in 96 bytes for sending
2020-03-11 08:57:28,283 - telethon.network.mtprotosender - DEBUG - Encrypted messages put in a queue to be sent
2020-03-11 08:57:28,283 - telethon.network.mtprotosender - DEBUG - Waiting for messages to send...
2020-03-11 08:57:28,283 - telethon.network.mtprotosender - DEBUG - Receiving items from the network...
2020-03-11 08:57:28,322 - telethon.network.mtprotosender - DEBUG - Handling bad salt for message 6802748226810135608
2020-03-11 08:57:28,322 - telethon.network.mtprotosender - DEBUG - 1 message(s) will be resent
2020-03-11 08:57:28,322 - telethon.network.mtprotosender - DEBUG - Receiving items from the network...
2020-03-11 08:57:28,323 - telethon.extensions.messagepacker - DEBUG - Assigned msg_id = 6802748226970848804 to InvokeWithLayerRequest (7f9d8ac93f60)
2020-03-11 08:57:28,323 - telethon.network.mtprotosender - DEBUG - Encrypting 1 message(s) in 96 bytes for sending
2020-03-11 08:57:28,323 - telethon.network.mtprotosender - DEBUG - Encrypted messages put in a queue to be sent
2020-03-11 08:57:28,323 - telethon.network.mtprotosender - DEBUG - Waiting for messages to send...
2020-03-11 08:57:28,323 - telethon.extensions.messagepacker - DEBUG - Assigned msg_id = 6802748226972458604 to MsgsAck (7f9d911ff978)
2020-03-11 08:57:28,323 - telethon.network.mtprotosender - DEBUG - Encrypting 1 message(s) in 36 bytes for sending
2020-03-11 08:57:28,323 - telethon.network.mtprotosender - DEBUG - Encrypted messages put in a queue to be sent
2020-03-11 08:57:28,323 - telethon.network.mtprotosender - DEBUG - Waiting for messages to send...
2020-03-11 08:57:28,362 - telethon.network.mtprotosender - DEBUG - Handling container
2020-03-11 08:57:28,362 - telethon.network.mtprotosender - DEBUG - Handling new session created
2020-03-11 08:57:28,362 - telethon.network.mtprotosender - DEBUG - Handling acknowledge for [6802748226970848804]
2020-03-11 08:57:28,363 - telethon.network.mtprotosender - DEBUG - Receiving items from the network...
2020-03-11 08:57:28,370 - telethon.network.mtprotosender - DEBUG - Handling RPC result for message 6802748226970848804
2020-03-11 08:57:28,371 - telethon.network.mtprotosender - DEBUG - Receiving items from the network...
2020-03-11 08:57:28,371 - telethon.extensions.messagepacker - DEBUG - Assigned msg_id = 6802748227165755036 to GetStateRequest (7f9d8ac93f28)
2020-03-11 08:57:28,371 - telethon.network.mtprotosender - DEBUG - Encrypting 1 message(s) in 20 bytes for sending
2020-03-11 08:57:28,372 - telethon.network.mtprotosender - DEBUG - Encrypted messages put in a queue to be sent
2020-03-11 08:57:28,372 - telethon.network.mtprotosender - DEBUG - Waiting for messages to send...
2020-03-11 08:57:28,372 - telethon.extensions.messagepacker - DEBUG - Assigned msg_id = 6802748227167873148 to MsgsAck (7f9d8acb89b0)
2020-03-11 08:57:28,372 - telethon.network.mtprotosender - DEBUG - Encrypting 1 message(s) in 60 bytes for sending
2020-03-11 08:57:28,372 - telethon.network.mtprotosender - DEBUG - Encrypted messages put in a queue to be sent
2020-03-11 08:57:28,372 - telethon.network.mtprotosender - DEBUG - Waiting for messages to send...
2020-03-11 08:57:28,447 - telethon.network.mtprotosender - DEBUG - Handling RPC result for message 6802748227165755036
2020-03-11 08:57:28,447 - telethon.network.mtprotosender - DEBUG - Receiving items from the network...
2020-03-11 08:57:28,448 - telethon.extensions.messagepacker - DEBUG - Assigned msg_id = 6802748227471258884 to GetDialogsRequest (7f9d8acb82e8)
2020-03-11 08:57:28,448 - telethon.network.mtprotosender - DEBUG - Encrypting 1 message(s) in 44 bytes for sending
2020-03-11 08:57:28,448 - telethon.network.mtprotosender - DEBUG - Encrypted messages put in a queue to be sent
2020-03-11 08:57:28,448 - telethon.network.mtprotosender - DEBUG - Waiting for messages to send...
2020-03-11 08:57:28,448 - telethon.extensions.messagepacker - DEBUG - Assigned msg_id = 6802748227472847704 to MsgsAck (7f9d8acb8470)
2020-03-11 08:57:28,448 - telethon.network.mtprotosender - DEBUG - Encrypting 1 message(s) in 36 bytes for sending
2020-03-11 08:57:28,448 - telethon.network.mtprotosender - DEBUG - Encrypted messages put in a queue to be sent
2020-03-11 08:57:28,448 - telethon.network.mtprotosender - DEBUG - Waiting for messages to send...
2020-03-11 08:57:28,860 - telethon.network.mtprotosender - DEBUG - Handling RPC result for message 6802748227471258884
2020-03-11 08:57:28,889 - telethon.network.mtprotosender - DEBUG - Receiving items from the network...
Traceback (most recent call last):
  File "forwardgram.py", line 49, in <module>
    start(config)
  File "forwardgram.py", line 23, in start
    if d.name in config["output_channel_names"]:
KeyError: 'output_channel_names'

**Comment by voidbar** [comment]
Hi! Thanks for the notice, i had a bug in the `config.yml-sample` file. I fixed the sample and now you should fill it as you like and it should be working :)
