### ISSUE TITLE
if d.name in config["input_channel_names"] or d.entity.i

### ISSUE THREAD

**Issue by devdeku** [voidbar/forwardgram#33]
python forwardgram.py config.yml
Traceback (most recent call last):
  File "H:\Python\18\forwardgram.py", line 49, in <module>
    start(config)
  File "H:\Python\18\forwardgram.py", line 21, in start
    if d.name in config["input_channel_names"] or d.entity.i
TypeError: 'in <string>' requires string as left operand, no

i'm having the following problem, can someone help me?

**Comment by devdeku** [comment]
> python forwardgram.py config.yml
> Traceback (most recent call last):
> File "H:\Python\18\forwardgram.py", line 49, in
> start(config)
> File "H:\Python\18\forwardgram.py", line 21, in start
> if d.name in config["input_channel_names"] or d.entity.i
> TypeError: 'in ' requires string as left operand, no
